### ISSUE TITLE
Compatibility with Python 3+

### ISSUE THREAD

**Issue by NishantNath-DemandMedia** [ctheiss/simple-requests#7]
Throws import error for compat module (can't import HTTPError)

**Comment by hasaziz** [comment]
Same here using python3:

ModuleNotFoundError: No module named 'compat'

**Comment by jeremyforan** [comment]
Same issue python3.7

**Comment by rodrigordgfs** [comment]
Last update was 6 years ago 🤦‍♂🤦‍♂🤦‍♂🤦‍♂

**Comment by ctheiss** [comment]
I've kept this issue open as a reminder to update the library when I had time.  I think we can all agree that's probably not going to happen, so this will remain Python2-only.

**Comment by jeremyforan** [comment]
Thanks for the update.
